version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400       # Plex web interface
      - 32469:32469       # DLNA
      - 1900:1900/udp     # DLNA discovery
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Moscow
    volumes:
      - /mnt/d/Plex Library:/data/media
      - plex_config:/config
    restart: unless-stopped

volumes:
  plex_config:
